### ISSUE TITLE
Работа №4

### ISSUE THREAD

**Issue by rpashkoff** [mipt-cs/course-algo#2]
Программа след занятия по С++, кто возмется написать? Отревьювить могу я.
Компиляторы С++. Краткий обзор
Ошибки компиляции и предупреждения. Опция -Wall.
Разбор hello_world.c
Ввод-вывод в потоки cin, cout, cerr.
Объявление переменных.
Циклы for и while.
Генерация арифметической и геометрической прогрессий.
Разложение числа на цифры.
Генерация псевдослучайных чисел
Запись в файл через ofstream.

**Comment by tkhirianov** [comment]
Закрываю карточку по таймауту. Уже прошла давно работа.
